# Generated by Django 5.0.2 on 2024-03-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytodo',
            old_name='datetimex',
            new_name='datetime',
        ),
    ]
