# Generated by Django 5.0.2 on 2024-03-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0002_rename_datetimex_mytodo_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytodo',
            name='myimage',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
